### ISSUE TITLE
I wonder how to learn to parse pptx, could you give me some direction ?

### ISSUE THREAD

**Issue by ruandao** [joswr1ght/pptxsanity#8]
[the ecma office open xml ](http://www.ecma-international.org/publications/standards/Ecma-376.htm) was too big to learn

some direction to quick start?

thank you!

**Comment by joswr1ght** [comment]
I made a tiny document, unzipped it, and started looking at the XML. Looking at my source may help a little, but really it's just a DIY struggle.
